[build]
  command = "npm install && npm run build && npm i serverless-http @netlify/functions @types/express"
  publish = "/public"

[functions]
  external_node_modules = ["express", "express-session", "compression", "body-parser", "cors", "cookie-parser", "youtubei.js"]

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
